import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, BookOpen, BrainCircuit, Code2, ExternalLink, Github, Menu, Plane, Radar, ScanFace, X } from "lucide-react";
import "../aerospace.css";

const BOOT = ["PORTFOLIO INTERFACE / JUDE DOMINIC YAP", "Loading project records...", "Loading training records...", "Interactive systems ready."];
const NAV = [["home", "Home"], ["about", "Profile"], ["projects", "Projects"], ["skills", "Skills"], ["training", "Training"], ["contact", "Links"]] as const;
const PROJECTS = [
  { number: "01", title: "Automated Facial Recognition System", type: "PYTHON / COMPUTER VISION / AI", icon: ScanFace, summary: "A completed project using Python, computer vision, and AI for automated facial recognition.", tags: ["Python", "Computer Vision", "AI"] },
  { number: "02", title: "Interactive Aerospace Portfolio", type: "REACT / TYPESCRIPT / WEB", icon: Plane, summary: "This React and TypeScript portfolio for documenting projects, training records, and an interest in aeronautical engineering.", tags: ["React", "TypeScript", "Web"] },
];
const SKILLS = [
  { title: "Python & Prototyping", icon: Code2, text: "Python programming and turning technical ideas into small prototypes." },
  { title: "AI & Computer Vision", icon: BrainCircuit, text: "Practical work with AI concepts, computer vision, and recognition systems." },
  { title: "Research & Documentation", icon: BookOpen, text: "STEM research, documentation, and communicating technical work clearly." },
];
const TRAINING = [
  ["Python Essentials 1", "Cisco Networking Academy", "2026"],
  ["Prompt Engineering Essentials", "FreeAcademy.ai", "2026"],
  ["Claude Projects Artifacts", "FreeAcademy.ai", "2026"],
  ["Introduction to Modern AI", "Cisco Networking Academy / DICT-ITU DTC", "2025"],
];
function scrollToId(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
export default function AerospacePortfolio() {
  const [booting, setBooting] = useState(true), [bootLine, setBootLine] = useState(0), [menuOpen, setMenuOpen] = useState(false), [activeNav, setActiveNav] = useState("home"), [activeProject, setActiveProject] = useState(0), [pulse, setPulse] = useState(false), [mouse, setMouse] = useState({ x: 50, y: 50 });
  const [legendPos, setLegendPos] = useState({ x: 0, y: 0 });
  const [legendReady, setLegendReady] = useState(false);
  const legendDrag = useRef({ active: false, offsetX: 0, offsetY: 0 });
  const deckRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const timer = window.setInterval(() => setBootLine((line) => { if (line >= BOOT.length - 1) { window.clearInterval(timer); window.setTimeout(() => setBooting(false), 350); return line; } return line + 1; }), 350); return () => window.clearInterval(timer); }, []);
  useEffect(() => { let frame = 0; const move = (event: MouseEvent) => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => { const x = Math.round((event.clientX / Math.max(window.innerWidth, 1)) * 100), y = Math.round((event.clientY / Math.max(window.innerHeight, 1)) * 100); setMouse({ x, y }); deckRef.current?.style.setProperty("--mx", `${event.clientX}px`); deckRef.current?.style.setProperty("--my", `${event.clientY}px`); }); }; window.addEventListener("mousemove", move, { passive: true }); return () => { cancelAnimationFrame(frame); window.removeEventListener("mousemove", move); }; }, []);
  useEffect(() => { const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActiveNav(visible.target.id); }, { threshold: [0.2, 0.55], rootMargin: "-12% 0px -58% 0px" }); NAV.forEach(([id]) => { const node = document.getElementById(id); if (node) observer.observe(node); }); return () => observer.disconnect(); }, []);
  useEffect(() => { if (typeof window !== "undefined") { setLegendPos({ x: Math.max(12, window.innerWidth - 230), y: 105 }); setLegendReady(true); } }, []);
  useEffect(() => { const move = (event: PointerEvent) => { if (!legendDrag.current.active) return; const maxX = Math.max(8, window.innerWidth - 210), maxY = Math.max(86, window.innerHeight - 250); setLegendPos({ x: Math.min(maxX, Math.max(8, event.clientX - legendDrag.current.offsetX)), y: Math.min(maxY, Math.max(82, event.clientY - legendDrag.current.offsetY)) }); }; const up = () => { legendDrag.current.active = false; document.body.classList.remove("legend-dragging"); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, []);
  const startLegendDrag = (event: React.PointerEvent<HTMLDivElement>) => { if ((event.target as HTMLElement).closest("button")) return; const rect = event.currentTarget.parentElement?.getBoundingClientRect(); if (!rect) return; legendDrag.current = { active: true, offsetX: event.clientX - rect.left, offsetY: event.clientY - rect.top }; event.currentTarget.setPointerCapture?.(event.pointerId); document.body.classList.add("legend-dragging"); };
  const coord = useMemo(() => `${mouse.x.toString().padStart(2, "0")} : ${mouse.y.toString().padStart(2, "0")}`, [mouse.x, mouse.y]);
  const selected = PROJECTS[activeProject], SelectedIcon = selected.icon;
  const particles = useMemo(() => Array.from({ length: 34 }, (_, i) => ({ id: i, x: (i * 37) % 100, y: (i * 61) % 100, delay: (i % 9) * -1.2, duration: 7 + (i % 7) })), []);
  const triggerPulse = () => { setPulse(true); window.setTimeout(() => setPulse(false), 1100); };
  return <div ref={deckRef} className={`flight-deck ${pulse ? "pulse-active" : ""}`}>
    <div className="hud-grid" aria-hidden="true" /><div className="texture-overlay" aria-hidden="true" /><div className="ambient-orb orb-violet" aria-hidden="true" /><div className="ambient-orb orb-cyan" aria-hidden="true" />
    <div className="particle-field" aria-hidden="true">{particles.map((p) => <i key={p.id} style={{ left: `${p.x}%`, top: `${p.y}%`, animationDelay: `${p.delay}s`, animationDuration: `${p.duration}s` }} />)}</div><div className="scanline" aria-hidden="true" />
    {booting && <div className="flight-boot" role="status" aria-live="polite"><div className="boot-panel"><div className="boot-label">✦ PORTFOLIO INTERFACE</div>{BOOT.slice(0, bootLine + 1).map((line) => <div className="boot-line" key={line}>{line}<span>_</span></div>)}<div className="boot-progress"><span style={{ width: `${((bootLine + 1) / BOOT.length) * 100}%` }} /></div></div></div>}
    <header className="flight-nav"><button className="flight-brand magnetic" onClick={() => scrollToId("home")} aria-label="Go to home"><span className="brand-mark"><Plane size={18} /></span><span><strong>J. DOMINIC YAP</strong><small>AERONAUTICAL ENGINEERING PORTFOLIO</small></span></button><nav className={menuOpen ? "flight-links open" : "flight-links"}>{NAV.map(([id, label]) => <button key={id} className={activeNav === id ? "active magnetic" : "magnetic"} onClick={() => { scrollToId(id); setMenuOpen(false); }}>{label}</button>)}</nav><div className="nav-status"><span>POINTER {coord}</span><i /><b>ACTIVE</b><button className="pulse-toggle magnetic" onClick={triggerPulse} aria-label="Trigger HUD pulse" title="Trigger HUD pulse">PULSE</button><button className="menu-button" onClick={() => setMenuOpen((value) => !value)} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    {legendReady && <aside className="section-legend section-legend-floating" style={{ left: legendPos.x, top: legendPos.y }} aria-label="Portfolio section map"><div className="legend-drag-handle" onPointerDown={startLegendDrag} title="Drag section map"><span className="legend-grip">⋮⋮</span><span><b>FLIGHT PATH</b><small>SECTION MAP · DRAG</small></span><span className="legend-live">LIVE</span></div><div className="legend-track">{NAV.map(([id, label], index) => <button key={id} className={activeNav === id ? "active" : ""} onClick={() => scrollToId(id)} aria-current={activeNav === id ? "page" : undefined}><span className="legend-node"><i /></span><span className="legend-label"><b>{String(index).padStart(2, "0")}</b>{label}</span></button>)}</div></aside>}
    <main>
      <section id="home" className="flight-hero"><div className="hero-hud"><span>POINTER X {mouse.x}%</span><span>POINTER Y {mouse.y}%</span><span>UI MODE ACTIVE</span></div><div className="hero-copy"><div className="eyebrow"><span /> GRADE 12 STEM · PHILIPPINES</div><p className="hero-kicker">ASPIRING AERONAUTICAL ENGINEER</p><h1>Building a future<br /><em>in flight.</em></h1><p className="hero-intro">I’m Jude Dominic Yap, a Grade 12 STEM student in the Philippines building skills in Python, AI, computer vision, and web development while preparing for a future in aeronautical engineering.</p><div className="hero-actions"><button className="flight-button primary magnetic" onClick={() => scrollToId("projects")}>EXPLORE PROJECTS <ArrowDown size={16} /></button><a className="flight-button magnetic" href="https://github.com/JudeDominicYap" target="_blank" rel="noreferrer">GITHUB <ExternalLink size={15} /></a></div><div className="hero-data"><div><span>GOAL</span><b>AERONAUTICAL ENGINEERING</b></div><div><span>CORE SKILL</span><b>PYTHON</b></div><div><span>APPROACH</span><b>LEARN · BUILD · DOCUMENT</b></div></div></div><div className="hero-visual radar-interactive" aria-label="Interactive compass radar"><div className="radar-core"><Radar size={48} /><span className="radar-sweep" /></div><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="visual-orbit orbit-three" /><div className="visual-crosshair" /><div className="aircraft-line"><span className="nose" /><span className="wing wing-top" /><span className="wing wing-bottom" /><span className="tail" /></div><div className="visual-label label-a">INTERACTIVE / RADAR</div><div className="visual-label label-b">MOUSE-REACTIVE SWEEP</div><div className="visual-coordinates">POINTER<br />{coord}</div></div><div className="hero-footer"><span>STATUS / LEARNING IN PROGRESS</span><span>PORTFOLIO / 2026</span><span>SCROLL TO EXPLORE ↓</span></div></section>
      <section id="about" className="flight-section about-section"><div className="section-head"><div><span className="section-code">00 / PROFILE</span><h2>Curious by nature.<br /><em>Engineering by direction.</em></h2></div><p>A factual snapshot of my current background, interests, and direction.</p></div><div className="about-grid"><div className="about-statement"><span className="big-index">01</span><p>I’m building foundations through <strong>Python, AI, computer vision, and web development.</strong></p></div><div className="about-facts"><div><span>IDENTITY</span><b>JUDE DOMINIC YAP</b></div><div><span>BACKGROUND</span><b>GRADE 12 STEM · PHILIPPINES</b></div><div><span>GOAL</span><b>ASPIRING AERONAUTICAL ENGINEER</b></div><div><span>INTERESTS</span><b>FLIGHT · AI · PYTHON · RESEARCH</b></div></div></div></section>
      <section id="projects" className="flight-section mission-section"><div className="section-head"><div><span className="section-code">01 / PROJECTS</span><h2>Work I’ve <em>built.</em></h2></div><p>Completed projects currently represented in this portfolio.</p></div><div className="mission-layout"><div className="mission-list">{PROJECTS.map((project, index) => { const Icon = project.icon; return <button key={project.title} className={index === activeProject ? "mission-card active" : "mission-card"} onClick={() => setActiveProject(index)}><span className="mission-number">{project.number}</span><span className="mission-icon"><Icon size={21} /></span><div><small>{project.type}</small><h3>{project.title}</h3><p>{project.summary}</p></div><ArrowUpRight size={19} /></button>; })}</div><div className="mission-detail"><div className="detail-top"><span>PROJECT / {selected.number}</span><span><i /> SELECTED</span></div><div className="detail-visual"><SelectedIcon size={76} strokeWidth={1} /><div className="detail-crosshair" /><span className="detail-scan" /></div><div className="detail-type">{selected.type}</div><h3>{selected.title}</h3><p>{selected.summary}</p><div className="tag-row">{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></div><div className="mission-nodes" aria-hidden="true"><i /><i /><i /><i /><i /></div></section>
      <section id="skills" className="flight-section skills-section"><div className="section-head"><div><span className="section-code">02 / SKILLS</span><h2>Tools for the <em>workbench.</em></h2></div><p>Core skills currently represented by my projects and training.</p></div><div className="systems-grid">{SKILLS.map((skill, index) => { const Icon = skill.icon; return <article className="system-card magnetic skill-pod" key={skill.title}><div className="system-top"><span>SKILL 0{index + 1}</span><span>ACTIVE</span></div><Icon size={25} /><h3>{skill.title}</h3><p>{skill.text}</p></article>; })}</div></section>
      <section id="training" className="flight-section training-section"><div className="section-head"><div><span className="section-code">03 / TRAINING</span><h2>Training <em>records.</em></h2></div><p>Training records supplied for this portfolio.</p></div><div className="training-table">{TRAINING.map(([title, provider, year], index) => <div className="training-row" key={title}><span>0{index + 1}</span><div><b>{title}</b><small>{provider}</small></div><time>{year}</time><span className="recorded">RECORDED</span></div>)}</div></section>
      <section id="contact" className="flight-section contact-section"><div className="contact-panel"><span className="section-code">04 / LINKS</span><h2>Find me<br /><em>online.</em></h2><p>Public links for my GitHub and LinkedIn profiles.</p><div className="contact-actions"><a className="flight-button primary magnetic" href="https://github.com/JudeDominicYap" target="_blank" rel="noreferrer"><Github size={16} /> GITHUB</a><a className="flight-button magnetic" href="https://www.linkedin.com/in/judedominicyap" target="_blank" rel="noreferrer">LINKEDIN <ExternalLink size={15} /></a></div></div></section>
    </main><footer className="flight-footer"><span>JUDE DOMINIC YAP / AERONAUTICAL ENGINEERING PORTFOLIO</span><span>REACT · TYPESCRIPT · WEB</span><span>POINTER {coord}</span></footer>
  </div>;
}
