import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, BookOpen, BrainCircuit, Code2, ExternalLink, Github, Menu, Plane, Radar, ScanFace, X } from "lucide-react";
import "../aerospace.css";

const BOOT = ["PORTFOLIO INTERFACE / JUDE DOMINIC YAP", "Loading project records...", "Loading training records...", "Interactive systems ready."];
const NAV = [["home", "Home"], ["about", "Profile"], ["projects", "Projects"], ["skills", "Skills"], ["training", "Training"], ["contact", "Links"]] as const;
const PROJECTS = [
  { number: "01", title: "Automated Facial Recognition System", type: "PYTHON / COMPUTER VISION / AI", icon: ScanFace, summary: "A completed project using Python, computer vision, and AI for automated facial recognition.", tags: ["Python", "Computer Vision", "AI"] },
  { number: "02", title: "Interactive Aerospace Portfolio", type: "REACT / TYPESCRIPT / WEB", icon: Plane, summary: "This React and TypeScript portfolio for documenting projects, training records, and an interest in aeronautical engineering.", tags: ["React", "TypeScript", "Web"] },
];
const SKILLS = [
  { title: "Python & Prototyping", icon: Code2, text: "Python programming and turning technical ideas into small prototypes." },
  { title: "AI & Computer Vision", icon: BrainCircuit, text: "Practical work with AI concepts, computer vision, and recognition systems." },
  { title: "Research & Documentation", icon: BookOpen, text: "STEM research, documentation, and communicating technical work clearly." },
];
const TRAINING = [
  ["Python Essentials 1", "Cisco Networking Academy", "2026"],
  ["Prompt Engineering Essentials", "FreeAcademy.ai", "2026"],
  ["Claude Projects Artifacts", "FreeAcademy.ai", "2026"],
  ["Introduction to Modern AI", "Cisco Networking Academy / DICT-ITU DTC", "2025"],
];
function scrollToId(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
const enhancementStyles = `
.section-legend-floating{position:fixed!important;z-index:75!important;transform:none!important;width:176px;padding:8px;border:1px solid rgba(152,181,40,.32);border-radius:10px;background:linear-gradient(145deg,rgba(19,27,46,.9),rgba(40,74,12,.72));backdrop-filter:blur(18px);box-shadow:0 18px 48px rgba(0,0,0,.38),inset 0 0 26px rgba(152,181,40,.05);user-select:none;overflow:hidden}.legend-drag-handle{display:grid;grid-template-columns:14px 1fr auto;gap:7px;align-items:center;min-height:31px;padding:4px 4px 7px;border-bottom:1px solid var(--line);cursor:grab;touch-action:none}.legend-drag-handle:active{cursor:grabbing}.legend-grip{color:var(--lime);font:700 13px/1 'DM Mono',monospace;letter-spacing:-5px}.legend-drag-handle b{display:block;color:var(--lime);font:600 8px/1 'DM Mono',monospace;letter-spacing:.14em}.legend-drag-handle small{display:block;margin-top:3px;color:var(--dim);font:7px/1 'DM Mono',monospace;letter-spacing:.09em}.legend-live{color:var(--cyan);font:600 6px/1 'DM Mono',monospace;letter-spacing:.12em}.legend-track{position:relative;padding-top:5px}.legend-track:before{content:'';position:absolute;left:10px;top:13px;bottom:13px;width:1px;background:linear-gradient(var(--lime),rgba(152,181,40,.08))}.legend-track button{position:relative;width:100%;display:grid;grid-template-columns:21px 1fr;gap:6px;align-items:center;border:0;background:none;padding:5px 3px;text-align:left;cursor:pointer;color:var(--dim);transition:color .2s,transform .2s}.legend-track button:hover,.legend-track button.active{color:var(--text);transform:translateX(2px)}.legend-node{position:relative;z-index:1;display:grid;place-items:center;width:13px;height:13px;border:1px solid rgba(152,181,40,.4);border-radius:50%;background:rgba(11,15,25,.92)}.legend-node i{width:3px;height:3px;border-radius:50%;background:var(--dim)}.legend-track button.active .legend-node{border-color:var(--lime);box-shadow:0 0 11px rgba(152,181,40,.28)}.legend-track button.active .legend-node i{background:var(--lime);box-shadow:0 0 7px var(--lime)}.legend-label{display:flex;align-items:center;gap:6px;font:7px 'DM Mono',monospace;letter-spacing:.08em}.legend-label b{font-weight:400;color:var(--amber);font-size:6px}.legend-dragging{cursor:grabbing!important}.legend-dragging *{cursor:grabbing!important}
.flight-section{isolation:isolate;overflow:visible;background:transparent!important}.flight-section:before{content:'';position:absolute;inset:0;z-index:-2;pointer-events:none;background:radial-gradient(650px 380px at 12% 12%,rgba(152,181,40,.14),transparent 68%),radial-gradient(520px 420px at 88% 80%,rgba(0,242,254,.055),transparent 70%),radial-gradient(500px 360px at 50% 105%,rgba(255,183,3,.045),transparent 72%),linear-gradient(145deg,rgba(72,116,19,.16),rgba(19,27,46,.24),rgba(11,15,25,.38))}.flight-section:after{content:'';position:absolute;inset:0;z-index:-1;pointer-events:none;background:linear-gradient(180deg,rgba(248,250,252,.015),transparent 18%,rgba(0,0,0,.2) 100%);box-shadow:inset 0 1px 0 rgba(152,181,40,.08),inset 0 55px 80px rgba(0,0,0,.08),0 -35px 70px rgba(0,0,0,.14),0 35px 70px rgba(0,0,0,.12)}.about-section:before{background:radial-gradient(650px 400px at 78% 18%,rgba(152,181,40,.16),transparent 70%),linear-gradient(145deg,rgba(18,42,7,.28),rgba(19,27,46,.28),rgba(11,15,25,.38))}.mission-section:before{background:radial-gradient(700px 430px at 14% 55%,rgba(0,242,254,.065),transparent 70%),radial-gradient(520px 360px at 80% 10%,rgba(72,116,19,.12),transparent 70%),linear-gradient(145deg,rgba(40,74,12,.18),rgba(19,27,46,.3),rgba(11,15,25,.4))}.skills-section:before{background:radial-gradient(700px 440px at 82% 45%,rgba(114,9,183,.09),transparent 70%),radial-gradient(500px 340px at 15% 15%,rgba(152,181,40,.08),transparent 70%),linear-gradient(145deg,rgba(19,27,46,.26),rgba(40,74,12,.16),rgba(11,15,25,.4))}.training-section:before{background:radial-gradient(620px 420px at 20% 30%,rgba(255,183,3,.055),transparent 70%),linear-gradient(145deg,rgba(40,74,12,.2),rgba(19,27,46,.3),rgba(11,15,25,.4))}.contact-section:before{background:radial-gradient(700px 450px at 78% 30%,rgba(152,181,40,.13),transparent 70%),radial-gradient(500px 350px at 18% 85%,rgba(0,242,254,.05),transparent 70%),linear-gradient(145deg,rgba(72,116,19,.18),rgba(19,27,46,.3),rgba(11,15,25,.4))}.about-statement,.about-facts,.mission-card,.mission-detail,.system-card,.contact-panel,.training-table{backdrop-filter:blur(10px);box-shadow:inset 0 0 45px rgba(152,181,40,.025),0 18px 45px rgba(0,0,0,.16)}.about-statement p{position:relative;left:auto;right:auto;bottom:auto;margin:105px 0 0;max-width:600px}.section-head>p,.mission-card p,.mission-detail p,.system-card p{overflow-wrap:anywhere}.mission-card h3,.mission-detail h3,.system-card h3{overflow-wrap:anywhere}.hero-copy{max-width:650px}.hero-intro{overflow-wrap:anywhere}.hero-data b{overflow-wrap:anywhere}.flight-hero{overflow:hidden}
@media(max-width:900px){.section-legend-floating{width:154px}.flight-section{padding-left:6vw;padding-right:6vw}.hero-copy{width:min(100%,600px)}.hero-visual{pointer-events:none}.about-statement p{margin-top:90px}}@media(max-width:620px){.section-legend-floating{width:148px}.legend-label{font-size:6.5px}.legend-drag-handle small{font-size:6px}.flight-section{padding-top:90px}.about-statement p{margin-top:80px}.section-head{gap:25px}.hero-intro{font-size:13px}.mission-card{min-width:0}.mission-card>div{min-width:0}.training-row>div{min-width:0}}@media(prefers-reduced-motion:reduce){.section-legend-floating,.flight-section:before,.flight-section:after{transition:none}}
`;
export default function AerospacePortfolio() {
  const [booting, setBooting] = useState(true), [bootLine, setBootLine] = useState(0), [menuOpen, setMenuOpen] = useState(false), [activeNav, setActiveNav] = useState("home"), [activeProject, setActiveProject] = useState(0), [pulse, setPulse] = useState(false), [mouse, setMouse] = useState({ x: 50, y: 50 });
  const [legendPos, setLegendPos] = useState({ x: 0, y: 0 });
  const legendDrag = useRef({ active: false, offsetX: 0, offsetY: 0 });
  const deckRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const timer = window.setInterval(() => setBootLine((line) => { if (line >= BOOT.length - 1) { window.clearInterval(timer); window.setTimeout(() => setBooting(false), 350); return line; } return line + 1; }), 350); return () => window.clearInterval(timer); }, []);
  useEffect(() => { let frame = 0; const move = (event: MouseEvent) => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => { const x = Math.round((event.clientX / Math.max(window.innerWidth, 1)) * 100), y = Math.round((event.clientY / Math.max(window.innerHeight, 1)) * 100); setMouse({ x, y }); deckRef.current?.style.setProperty("--mx", `${event.clientX}px`); deckRef.current?.style.setProperty("--my", `${event.clientY}px`); }); }; window.addEventListener("mousemove", move, { passive: true }); return () => { cancelAnimationFrame(frame); window.removeEventListener("mousemove", move); }; }, []);
  useEffect(() => { const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActiveNav(visible.target.id); }, { threshold: [0.2, 0.55], rootMargin: "-12% 0px -58% 0px" }); NAV.forEach(([id]) => { const node = document.getElementById(id); if (node) observer.observe(node); }); return () => observer.disconnect(); }, []);
  useEffect(() => { const setInitial = () => setLegendPos({ x: Math.max(8, window.innerWidth - 198), y: Math.min(180, Math.max(90, window.innerHeight * .16)) }); setInitial(); window.addEventListener("resize", setInitial); return () => window.removeEventListener("resize", setInitial); }, []);
  useEffect(() => { const move = (event: PointerEvent) => { if (!legendDrag.current.active) return; const width = window.innerWidth < 620 ? 148 : window.innerWidth < 900 ? 154 : 176; const maxX = Math.max(8, window.innerWidth - width - 8), maxY = Math.max(84, window.innerHeight - 245); setLegendPos({ x: Math.min(maxX, Math.max(8, event.clientX - legendDrag.current.offsetX)), y: Math.min(maxY, Math.max(82, event.clientY - legendDrag.current.offsetY)) }); }; const up = () => { legendDrag.current.active = false; document.body.classList.remove("legend-dragging"); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, []);
  const startLegendDrag = (event: React.PointerEvent<HTMLDivElement>) => { const rect = event.currentTarget.parentElement?.getBoundingClientRect(); if (!rect) return; legendDrag.current = { active: true, offsetX: event.clientX - rect.left, offsetY: event.clientY - rect.top }; document.body.classList.add("legend-dragging"); };
  const coord = useMemo(() => `${mouse.x.toString().padStart(2, "0")} : ${mouse.y.toString().padStart(2, "0")}`, [mouse.x, mouse.y]);
  const selected = PROJECTS[activeProject], SelectedIcon = selected.icon;
  const particles = useMemo(() => Array.from({ length: 34 }, (_, i) => ({ id: i, x: (i * 37) % 100, y: (i * 61) % 100, delay: (i % 9) * -1.2, duration: 7 + (i % 7) })), []);
  const triggerPulse = () => { setPulse(true); window.setTimeout(() => setPulse(false), 1100); };
  return <div ref={deckRef} className={`flight-deck ${pulse ? "pulse-active" : ""}`}>
    <style>{enhancementStyles}</style>
    <div className="hud-grid" aria-hidden="true" /><div className="texture-overlay" aria-hidden="true" /><div className="ambient-orb orb-violet" aria-hidden="true" /><div className="ambient-orb orb-cyan" aria-hidden="true" />
    <div className="particle-field" aria-hidden="true">{particles.map((p) => <i key={p.id} style={{ left: `${p.x}%`, top: `${p.y}%`, animationDelay: `${p.delay}s`, animationDuration: `${p.duration}s` }} />)}</div><div className="scanline" aria-hidden="true" />
    {booting && <div className="flight-boot" role="status" aria-live="polite"><div className="boot-panel"><div className="boot-label">✦ PORTFOLIO INTERFACE</div>{BOOT.slice(0, bootLine + 1).map((line) => <div className="boot-line" key={line}>{line}<span>_</span></div>)}<div className="boot-progress"><span style={{ width: `${((bootLine + 1) / BOOT.length) * 100}%` }} /></div></div></div>}
    <header className="flight-nav"><button className="flight-brand magnetic" onClick={() => scrollToId("home")} aria-label="Go to home"><span className="brand-mark"><Plane size={18} /></span><span><strong>J. DOMINIC YAP</strong><small>AERONAUTICAL ENGINEERING PORTFOLIO</small></span></button><nav className={menuOpen ? "flight-links open" : "flight-links"}>{NAV.map(([id, label]) => <button key={id} className={activeNav === id ? "active magnetic" : "magnetic"} onClick={() => { scrollToId(id); setMenuOpen(false); }}>{label}</button>)}</nav><div className="nav-status"><span>POINTER {coord}</span><i /><b>ACTIVE</b><button className="pulse-toggle magnetic" onClick={triggerPulse} aria-label="Trigger HUD pulse" title="Trigger HUD pulse">PULSE</button><button className="menu-button" onClick={() => setMenuOpen((value) => !value)} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <aside className="section-legend section-legend-floating" style={{ left: legendPos.x, top: legendPos.y }} aria-label="Portfolio section map"><div className="legend-drag-handle" onPointerDown={startLegendDrag} title="Drag section map"><span className="legend-grip">⋮⋮</span><span><b>FLIGHT PATH</b><small>SECTION MAP · DRAG</small></span><span className="legend-live">LIVE</span></div><div className="legend-track">{NAV.map(([id, label], index) => <button key={id} className={activeNav === id ? "active" : ""} onClick={() => scrollToId(id)} aria-current={activeNav === id ? "page" : undefined}><span className="legend-node"><i /></span><span className="legend-label"><b>{String(index).padStart(2, "0")}</b>{label}</span></button>)}</div></aside>
    <main>
      <section id="home" className="flight-hero"><div className="hero-hud"><span>POINTER X {mouse.x}%</span><span>POINTER Y {mouse.y}%</span><span>UI MODE ACTIVE</span></div><div className="hero-copy"><div className="eyebrow"><span /> GRADE 12 STEM · PHILIPPINES</div><p className="hero-kicker">ASPIRING AERONAUTICAL ENGINEER</p><h1>Building a future<br /><em>in flight.</em></h1><p className="hero-intro">I’m Jude Dominic Yap, a Grade 12 STEM student in the Philippines building skills in Python, AI, computer vision, and web development while preparing for a future in aeronautical engineering.</p><div className="hero-actions"><button className="flight-button primary magnetic" onClick={() => scrollToId("projects")}>EXPLORE PROJECTS <ArrowDown size={16} /></button><a className="flight-button magnetic" href="https://github.com/JudeDominicYap" target="_blank" rel="noreferrer">GITHUB <ExternalLink size={15} /></a></div><div className="hero-data"><div><span>GOAL</span><b>AERONAUTICAL ENGINEERING</b></div><div><span>CORE SKILL</span><b>PYTHON</b></div><div><span>APPROACH</span><b>LEARN · BUILD · DOCUMENT</b></div></div></div><div className="hero-visual radar-interactive" aria-label="Interactive compass radar"><div className="radar-core"><Radar size={48} /><span className="radar-sweep" /></div><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="visual-orbit orbit-three" /><div className="visual-crosshair" /><div className="aircraft-line"><span className="nose" /><span className="wing wing-top" /><span className="wing wing-bottom" /><span className="tail" /></div><div className="visual-label label-a">INTERACTIVE / RADAR</div><div className="visual-label label-b">MOUSE-REACTIVE SWEEP</div><div className="visual-coordinates">POINTER<br />{coord}</div></div><div className="hero-footer"><span>STATUS / LEARNING IN PROGRESS</span><span>PORTFOLIO / 2026</span><span>SCROLL TO EXPLORE ↓</span></div></section>
      <section id="about" className="flight-section about-section"><div className="section-head"><div><span className="section-code">00 / PROFILE</span><h2>Curious by nature.<br /><em>Engineering by direction.</em></h2></div><p>A factual snapshot of my current background, interests, and direction.</p></div><div className="about-grid"><div className="about-statement"><span className="big-index">01</span><p>I’m building foundations through <strong>Python, AI, computer vision, and web development.</strong></p></div><div className="about-facts"><div><span>IDENTITY</span><b>JUDE DOMINIC YAP</b></div><div><span>BACKGROUND</span><b>GRADE 12 STEM · PHILIPPINES</b></div><div><span>GOAL</span><b>ASPIRING AERONAUTICAL ENGINEER</b></div><div><span>INTERESTS</span><b>FLIGHT · AI · PYTHON · RESEARCH</b></div></div></div></section>
      <section id="projects" className="flight-section mission-section"><div className="section-head"><div><span className="section-code">01 / PROJECTS</span><h2>Work I’ve <em>built.</em></h2></div><p>Completed projects currently represented in this portfolio.</p></div><div className="mission-layout"><div className="mission-list">{PROJECTS.map((project, index) => { const Icon = project.icon; return <button key={project.title} className={index === activeProject ? "mission-card active" : "mission-card"} onClick={() => setActiveProject(index)}><span className="mission-number">{project.number}</span><span className="mission-icon"><Icon size={21} /></span><div><small>{project.type}</small><h3>{project.title}</h3><p>{project.summary}</p></div><ArrowUpRight size={19} /></button>; })}</div><div className="mission-detail"><div className="detail-top"><span>PROJECT / {selected.number}</span><span><i /> SELECTED</span></div><div className="detail-visual"><SelectedIcon size={76} strokeWidth={1} /><div className="detail-crosshair" /><span className="detail-scan" /></div><div className="detail-type">{selected.type}</div><h3>{selected.title}</h3><p>{selected.summary}</p><div className="tag-row">{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></div><div className="mission-nodes" aria-hidden="true"><i /><i /><i /><i /><i /></div></section>
      <section id="skills" className="flight-section skills-section"><div className="section-head"><div><span className="section-code">02 / SKILLS</span><h2>Tools for the <em>workbench.</em></h2></div><p>Core skills currently represented by my projects and training.</p></div><div className="systems-grid">{SKILLS.map((skill, index) => { const Icon = skill.icon; return <article className="system-card magnetic skill-pod" key={skill.title}><div className="system-top"><span>SKILL 0{index + 1}</span><span>ACTIVE</span></div><Icon size={25} /><h3>{skill.title}</h3><p>{skill.text}</p></article>; })}</div></section>
      <section id="training" className="flight-section training-section"><div className="section-head"><div><span className="section-code">03 / TRAINING</span><h2>Training <em>records.</em></h2></div><p>Training records supplied for this portfolio.</p></div><div className="training-table">{TRAINING.map(([title, provider, year], index) => <div className="training-row" key={title}><span>0{index + 1}</span><div><b>{title}</b><small>{provider}</small></div><time>{year}</time><span className="recorded">RECORDED</span></div>)}</div></section>
      <section id="contact" className="flight-section contact-section"><div className="contact-panel"><span className="section-code">04 / LINKS</span><h2>Find me<br /><em>online.</em></h2><p>Public links for my GitHub and LinkedIn profiles.</p><div className="contact-actions"><a className="flight-button primary magnetic" href="https://github.com/JudeDominicYap" target="_blank" rel="noreferrer"><Github size={16} /> GITHUB</a><a className="flight-button magnetic" href="https://www.linkedin.com/in/judedominicyap" target="_blank" rel="noreferrer">LINKEDIN <ExternalLink size={15} /></a></div></div></section>
    </main><footer className="flight-footer"><span>JUDE DOMINIC YAP / AERONAUTICAL ENGINEERING PORTFOLIO</span><span>REACT · TYPESCRIPT · WEB</span><span>POINTER {coord}</span></footer>
  </div>;
}
